### ISSUE TITLE
Damaged car price

### ISSUE THREAD

**Issue by lucasvperini** [JustAnotherModder/JAM_Garage#2]
Hey!

Does this store damaged cars? Asks for repair price?

Thanks!

**Comment by JustAnotherModder** [comment]
It stores damaged cars, it doesn't make the player pay for repairs.

**Comment by lucasvperini** [comment]
> It stores damaged cars, it doesn't make the player pay for repairs.

It's possible to add this function?

**Comment by JustAnotherModder** [comment]
I'm sure it would be, but I thought it was an unnecessary taxing of players money in an already overly-grindy environment (speaking for most RP servers). I decided to leave it out, because I don't want somebody who is using my base mod, unedited, to experience the annoyance of running out of money because GTA 5 vehicles handle like boats.

**Comment by lucasvperini** [comment]
Can i ask you to add this function? Maybe with a boolean for it on config file...
Thanks! :D

**Comment by JustAnotherModder** [comment]
I can take a look over the next few days when I have time--
What exactly are you after?
Pay for vehicle repairs based on damage done to vehicle?
Call a mechanic (if that job is even available)?

Also, are you requesting this as a player of a server, who actually grinds their money, or as a server owner who wishes for their players to be taxed at every corner? << This question is important to me.

**Comment by frenchy77700** [comment]
I would like the same function for my server to . I am a founder and we use the mechanic job , and since the players can put the cars away damaged and pulls them out immediatley repaired well our poor mechanics end up doing nothing . so yeah would be a realy good adition even in config to turn on and off if needed . For me personaly i like my players to grind a bit for there money it keeps them active in the server . And i might be pushing my luck by asking this question but is it possible to add a way of renaming the vehicle names seing that i have a couple of addons , Ok only addons , the players get lost quickly in the listing :/ Sorry again for the questions and thank you for the script it works like a charm for me ^^

**Comment by lucasvperini** [comment]
@JustAnotherModder i want to increase the mechanic job interaction and balance the economy. It's too easy to players just screw up the car, go to the garage and take it again as new...
I think that if the car "state" gets stored, will be awesome, so the players will need to call a mechanic or pay a tax to repair the car.
Will be awesome!
Thank you!
(sorry for my bad english, i'm brazilian).

**Comment by JustAnotherModder** [comment]
I'll add an option for this in the future (working on something else right now). Not sure about restoring the damage of vehicles when removing from garage, though.
